### ISSUE TITLE
Code redundancy

### ISSUE THREAD

**Issue by goors** [sauerbraten/crudapi#7]
You have code redundancy everywhere.
For example create/update everything is the same except one line of code 
<pre>    
id, stoResp := s.Create(vars["kind"], resource)
stoResp := s.Update(vars["kind"], vars["id"], resource)
</pre>
Everything else is same.
After that you have 
<pre>   
    authenticatedAndAuthorized, vars, enc := initHandling(req, resp, ActionUpdate)
	if !authenticatedAndAuthorized {
		return
	}
</pre>   
in every func.

I am just trying to keep my code without any redundacy and i can see you have lot of it.
I thing main reason for that is go does not support optional params in func.

DO you have maybe idea how to solve this?

**Comment by sauerbraten** [comment]
Actually, I have. I'll try to reduce code redundancy by using context-wrapping functions.
