### ISSUE TITLE
inserts too fast give the same ID

### ISSUE THREAD

**Issue by formvoltron** [sauerbraten/crudapi#8]
I'd like to use a shell script to "boot" my demo crud rest server.

when i insert records too fast, then i get back the same ID with each.

**Comment by sauerbraten** [comment]
What Storage implementation do you use? The example map storage solution used the current Unix timestamp as IDs for newly created things. If you use that, check if https://github.com/sauerbraten/crudapi/commit/2e163190e7084d404a9dd1e26fb89bae831ae180 fixes your problem.
